name: Deploy to Replit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: DaInfLoop/Replit-Deployments@0fe797477997e6aefaa20bd1afc9a93b47f891b1
        with:
          replId: cdb7e6c7-516b-4a4b-b7c3-24fbc90f6805
          token: ${{ secrets.REPLIT_TOKEN }}
          subdomain: xela-nft
          runCommand: python index.py
